// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClJZ0JulgZ1k__V2UwrA4y15fBqpNvI-U',
    appId: '1:820058616610:web:11ae9842df14c05d21ab7b',
    messagingSenderId: '820058616610',
    projectId: 'macquarie-app',
    authDomain: 'macquarie-app.firebaseapp.com',
    storageBucket: 'macquarie-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAv6UHh95gqohRT8PXio0aLr_RINCpi0aM',
    appId: '1:820058616610:android:4c266b749fe0642921ab7b',
    messagingSenderId: '820058616610',
    projectId: 'macquarie-app',
    storageBucket: 'macquarie-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkO9Ezi5IyOPS7mrE6wXdDm48e_JhikEM',
    appId: '1:820058616610:ios:79fcef804c33ed3821ab7b',
    messagingSenderId: '820058616610',
    projectId: 'macquarie-app',
    storageBucket: 'macquarie-app.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkO9Ezi5IyOPS7mrE6wXdDm48e_JhikEM',
    appId: '1:820058616610:ios:79fcef804c33ed3821ab7b',
    messagingSenderId: '820058616610',
    projectId: 'macquarie-app',
    storageBucket: 'macquarie-app.appspot.com',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClJZ0JulgZ1k__V2UwrA4y15fBqpNvI-U',
    appId: '1:820058616610:web:db3ccbe502c23f7521ab7b',
    messagingSenderId: '820058616610',
    projectId: 'macquarie-app',
    authDomain: 'macquarie-app.firebaseapp.com',
    storageBucket: 'macquarie-app.appspot.com',
  );

}